### ISSUE TITLE
What is the most exciting application of blockchains in the education sector?

### ISSUE THREAD

**Issue by hathawayjess** [usedgov/blockchain#1]

**Comment by djuanit0x** [comment]
Student Loans (https://github.com/onggunhao/enable))

**Comment by Custard7** [comment]
Creating an open, transparent value transfer protocol around learning and education outcomes to empower students to have control over their own data and transcripts, fuel intelligent human capital investment, and unlock new models where students can earn equity as they learn! If you're interested in getting involved, checkout [Learning Economy](www.learningeconomy.io)

**Comment by tkendal** [comment]
> Student Loans [Here](https://github.com/onggunhao/enable)

@djuanit0x Are you affiliated with Enable? Would there be interest in connecting this project to the US EdGov repo and gaining insight form this community?

**Comment by BlueLeiLani** [comment]
Blockchain is really only a chain-of-trust code structure, and ideologically is a transactional tech arena.  Chain-of-trust replaces institution-of-trust as a progressive idea.  Block chain's highest achievement in education could be the complete unraveling of institutions in favor of a direct student agency that is Uber and Amazon-like.  The trust then becomes the learning object/resource itself as a method/rigor.  OR, becomes the stature of the mentor/teacher.  Udemy and Khan Academy have proven that the institution (the site) is irrelevant to the learning consumer when learning is on-demand.  They just want the learning.  The fact of the transaction completion alone will be a first area, but that doesn't require block-chain, just a trust hub.  Is this initiative trying to discover ways to provide chains of evidence?  If so, I predict that has a life-cycle that is only about 10 years at best.  The disintermediation of the institutions of learning, as in retail and all other industries, is already under way.  There are more important trust areas to worry about and they are ideosyncratic to the code structure of individual resources and the commercialization of trust in learning.  That is the largest and most glaring inefficiency, and the Feds can't really do much in that area because they can't predispose commerce, although some workarounds doing just that are still operating to divert attention from the real work of digital ascendency in education via the HE Opp Act of 1965 snuck-in feature.  Digital Promise anyone?  What a diversion in the direction of specious busywork without any real change so that the big tech companies could dominate the landscape of ed-tech and Silicon Valley investors could presuppose the directionality of all investment through ASU/GSV, a single bank running amok behind the cloak of a University.  The last eight years of their dominance has gutted a lot of the innovation and voice in American ed-tech.  In any case, chain-of-trust of records alone props up a system of institutional certification rather than distributed and more vague credits adjudicated for merit individually.  Since academic standards are not a concrete foundation, that will be the only outcome, so again, disintermediation of institutions and a potential block-chain that the only worth will be the fact of a transaction between two entities, whether individual-to-individual or individual-to-institutions -- meaningfulness of that transaction will forever be in question.  And you don't need block chain to prove a transaction.  Only a clearinghouse, same as the banks use.  I have been discussing block-chain with all my developers for five years now, and in every lengthy discussion when it gets down to the code actually needed to deliver on the outcome desired, they all drop block-chain like a hot rock.  It's not needed for what's really needed.  What's really needed is a real change in the distribution mechanism of learning -- and until that is fully understood in human context against the realities of screen learning and algorithmically-generated interactions that actually do the majority of the "teaching," what will be done will be a tack-on only.  The real revolution is a change in structure.

**Comment by MollySumner** [comment]
Speculative investments in human capital, of course. The hedge funds need somewhere to put their concentrated wealth. https://wrenchinthegears.com/2018/08/13/edu-blocks-arrive-in-new-hampshire/
