### ISSUE TITLE
How can we ensure that blockchains can be used to create an education system that is equitable and accessible to all students?

### ISSUE THREAD

**Issue by hathawayjess** [usedgov/blockchain#3]

**Comment by Custard7** [comment]
Governance is key and can't be an afterthought. Equitable governance models must be baked directly into any education blockchain protocols and the organizations stewarding their development.

**Comment by tkendal** [comment]
@Custard7 Absolutely! Is there a need for a single model governance template or should the governance models be entirely custom and as varied as the systems for which they influence?

**Comment by massadon77** [comment]
@Custard7  I think an appropriate business model to use blockchains properly.  I hope an appropriate business model is developed so that education data is owned by the individuals and blockchains are utilized as the distributed ledger.  If not, governments or big guys (GAFA & BAT) will own and use the big data, for their benefits.
